# Generated by Django 4.2.3 on 2023-07-24 15:30

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('popularity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mailing_address', models.CharField(max_length=100, null=True)),
                ('max_reservations', models.IntegerField(default=30)),
                ('current_reservations', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstoreapi.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstoreapi.customer')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['customer'], name='bookstoreap_custome_b97d1e_hash'), django.contrib.postgres.indexes.HashIndex(fields=['book'], name='bookstoreap_book_id_b7b3e4_hash')],
            },
        ),
    ]
